do not build with pci
To fix this build error:
```
/usr/bin/ld.bfd: ocaml-hwloc/src/c/libhwloc.a(topology-pci.o): in function `hwloc_look_pci.part.0':
topology-pci.c:(.text+0x61): undefined reference to `pci_system_init'
/usr/bin/ld.bfd: topology-pci.c:(.text+0x70): undefined reference to `pci_slot_match_iterator_create'
/usr/bin/ld.bfd: topology-pci.c:(.text+0x7d): undefined reference to `pci_device_next'
/usr/bin/ld.bfd: topology-pci.c:(.text+0x1f4): undefined reference to `pci_device_get_vendor_name'
/usr/bin/ld.bfd: topology-pci.c:(.text+0x211): undefined reference to `pci_device_get_device_name'
/usr/bin/ld.bfd: topology-pci.c:(.text+0x277): undefined reference to `pci_device_next'
/usr/bin/ld.bfd: topology-pci.c:(.text+0x2f6): undefined reference to `pci_device_probe'
/usr/bin/ld.bfd: topology-pci.c:(.text+0x30b): undefined reference to `pci_device_cfg_read'
/usr/bin/ld.bfd: topology-pci.c:(.text+0x5bc): undefined reference to `pci_device_get_device_name'
/usr/bin/ld.bfd: topology-pci.c:(.text+0x5fe): undefined reference to `pci_device_get_device_name'
/usr/bin/ld.bfd: topology-pci.c:(.text+0x69b): undefined reference to `pci_iterator_destroy'
/usr/bin/ld.bfd: topology-pci.c:(.text+0x6a0): undefined reference to `pci_system_cleanup'
```

Alternatively we could add `-cclib -lpciaccess`, but that'd depend on
whether you have libpciaccess-devel installed or not.

Signed-off-by: Edwin Török <edwin@tarides.com>